# Generated by Django 5.2.16 on 2026-08-04 13:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Commission Amount ($)')),
                ('level', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Referral Level (1–5)')),
                ('commission_type', models.CharField(choices=[('DIRECT', 'Direct Income (2%)'), ('ROI', 'ROI Income (1.5%)')], db_index=True, max_length=20, verbose_name='Commission Type')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Is Paid to Wallet')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Source User (Who Triggered It)')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='investments.investment', verbose_name='Source Investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User')),
            ],
            options={
                'verbose_name': 'Referral Commission',
                'verbose_name_plural': 'Referral Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'commission_type'], name='referrals_r_user_id_83ce9b_idx'), models.Index(fields=['user', 'is_paid'], name='referrals_r_user_id_37ccc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Sponsor / Parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_relationship', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Relationship',
                'verbose_name_plural': 'Referral Relationships',
                'indexes': [models.Index(fields=['sponsor'], name='referrals_r_sponsor_c217ea_idx')],
            },
        ),
    ]
