# Generated by Django 5.2.16 on 2026-08-04 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('INVESTMENT', 'Investment'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('REFERRAL', 'Referral'), ('ANNOUNCEMENT', 'Announcement'), ('KYC', 'KYC')], db_index=True, default='SYSTEM', max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('is_broadcast', models.BooleanField(db_index=True, default=False, verbose_name='Is Broadcast')),
                ('reference_id', models.CharField(blank=True, help_text='UUID of the related object for deep-linking', max_length=100, verbose_name='Reference ID')),
                ('user', models.ForeignKey(blank=True, help_text='Null for broadcast notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
