# Generated by Django 5.2.16 on 2026-08-04 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Key')),
                ('value', models.TextField(verbose_name='Value')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_updates', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_APPROVED', 'Investment Approved'), ('INVESTMENT_REJECTED', 'Investment Rejected'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('DEPOSIT_SUBMITTED', 'Deposit Submitted'), ('DEPOSIT_APPROVED', 'Deposit Approved'), ('DEPOSIT_REJECTED', 'Deposit Rejected'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('WALLET_CREDITED', 'Wallet Credited'), ('WALLET_DEBITED', 'Wallet Debited'), ('ROI_DISTRIBUTED', 'ROI Distributed'), ('ADMIN_ACTION', 'Admin Action'), ('SETTINGS_UPDATED', 'Settings Updated')], db_index=True, max_length=50, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='New Value')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Extra Data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='core_auditl_user_id_4f5b78_idx'), models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx')],
            },
        ),
    ]
