# Generated by Django 5.2.16 on 2026-08-04 13:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount ($)')),
                ('network', models.CharField(choices=[('BEP20', 'BEP20 (BSC)'), ('TRC20', 'TRC20 (TRON)')], max_length=10, verbose_name='Network')),
                ('sender_wallet_address', models.CharField(blank=True, max_length=200, verbose_name='Sender Wallet Address')),
                ('txn_hash', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Transaction Hash')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='deposits/', verbose_name='Payment Proof')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deposits', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='transaction_user_id_d05eaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Requested Amount ($)')),
                ('withdrawal_type', models.CharField(choices=[('PROFIT', 'Profit Withdrawal'), ('CAPITAL', 'Capital Withdrawal')], db_index=True, default='PROFIT', max_length=10, verbose_name='Withdrawal Type')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='$1 per withdrawal per SRS', max_digits=18, verbose_name='Transaction Fee ($)')),
                ('capital_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='$10 fund-management charge for capital withdrawals', max_digits=18, verbose_name='Capital Withdrawal Charge ($)')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='amount - fee - capital_charge', max_digits=18, verbose_name='Net Amount ($)')),
                ('network', models.CharField(choices=[('BEP20', 'BEP20 (BSC)'), ('TRC20', 'TRC20 (TRON)')], max_length=10, verbose_name='Network')),
                ('wallet_address', models.CharField(max_length=200, verbose_name='Destination Wallet Address')),
                ('txn_hash', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Transaction Hash')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='transaction_user_id_3710aa_idx')],
            },
        ),
    ]
