# Generated by Django 5.2.17 on 2026-08-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_country_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KYC Document Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_document_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='KYC Document Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='KYC Rejection Reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC Submitted At'),
        ),
    ]
