# Generated by Django 5.2.16 on 2026-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_kyc_document_number_user_kyc_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kyc_document',
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_document_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/back/', verbose_name='KYC Document Back'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_document_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/front/', verbose_name='KYC Document Front'),
        ),
    ]
