# Generated by Django 5.2.16 on 2026-08-04 13:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Available Balance ($)')),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Deposited ($)')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Withdrawn ($)')),
                ('total_roi_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total ROI Earned ($)')),
                ('total_direct_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Direct Income ($)')),
                ('total_referral_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Referral Income ($)')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Invested ($)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('category', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ROI', 'ROI Income'), ('DIRECT_INCOME', 'Direct Income'), ('REFERRAL_INCOME', 'Referral Income'), ('CAPITAL_WITHDRAWAL', 'Capital Withdrawal'), ('FEE', 'Fee Deduction'), ('ADJUSTMENT', 'Admin Adjustment')], db_index=True, max_length=30, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount ($)')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Balance Before ($)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Balance After ($)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='UUID of the source object (Deposit, Withdrawal, Investment, etc.)', max_length=100, verbose_name='Reference ID')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'category'], name='wallet_wall_wallet__8f56b6_idx'), models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__83a8d3_idx')],
            },
        ),
    ]
