# Generated by Django 5.2.17 on 2026-08-21 21:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='team_total_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='5-Level Team Investment ($)'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='team_total_members',
            field=models.IntegerField(default=0, verbose_name='5-Level Team Members'),
        ),
    ]
