# Generated by Django 5.2.16 on 2026-08-04 13:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Minimum Investment Amount ($)')),
                ('maximum_amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Maximum Investment Amount ($)')),
                ('max_total_return', models.DecimalField(decimal_places=2, default=Decimal('350.00'), help_text='Investment stops crediting once this amount is reached. Default: $350', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Maximum Total Return ($) (Capital Included)')),
                ('weekly_roi_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Percentage credited to wallet each Saturday', max_digits=7, verbose_name='Weekly ROI Rate (%)')),
                ('duration_weeks', models.PositiveIntegerField(default=0, help_text='0 means open-ended until max return is reached', verbose_name='Duration (Weeks)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Principal Amount ($)')),
                ('max_return', models.DecimalField(decimal_places=2, help_text='Copied from plan at the time of investment', max_digits=18, verbose_name='Maximum Total Return ($)')),
                ('total_credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running sum of all ROI payments made. Investment closes when this reaches max_return.', max_digits=18, verbose_name='Total Credited ($)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('last_roi_date', models.DateField(blank=True, help_text='Date of the last weekly ROI distribution', null=True, verbose_name='Last ROI Date')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_investments', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'), models.Index(fields=['status', 'created_at'], name='investments_status_93af78_idx')],
            },
        ),
    ]
