# Generated by Django 5.2.16 on 2026-08-17 14:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_deposit_proof'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investment',
            new_name='investments_user_id_9e7652_idx',
            old_name='investments_user_start_date_idx',
        ),
        migrations.AlterField(
            model_name='investment',
            name='total_credited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running sum of all ROI payments + referral income credited to this plan. Investment closes when this reaches max_return.', max_digits=18, verbose_name='Total Credited ($)'),
        ),
    ]
